#!/usr/bin/env python3
"""Generate @font-face CSS from local font assets for kairos-wechat-typeset."""

import argparse
import json
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = SKILL_ROOT / "assets" / "fonts"

FONT_FACE_TEMPLATE = """@font-face {{
  font-family: '{family}';
  src: url('{url}') format('{format}');
  font-weight: {weight};
  font-style: {style};
  font-display: swap;
}}"""


def load_registry() -> dict:
    registry_path = FONTS_DIR / "fonts.json"
    if not registry_path.exists():
        print(f"Error: Registry not found at {registry_path}", file=sys.stderr)
        sys.exit(1)
    return json.loads(registry_path.read_text(encoding="utf-8"))


def family_name(font: dict) -> str:
    return font["name"]


def build_font_faces(registry: dict) -> str:
    declarations = []
    for font in registry.get("fonts", []):
        font_path = FONTS_DIR / font["path"]
        if not font_path.exists():
            print(f"Warning: Font file not found: {font_path}", file=sys.stderr)
            continue

        rel_path = f"../{font['path']}"

        declarations.append(
            FONT_FACE_TEMPLATE.format(
                family=family_name(font),
                url=rel_path,
                format=font.get("format", "woff2"),
                weight=font.get("weight", "400"),
                style=font.get("style", "normal"),
            )
        )

    header = "/* Auto-generated by build_font_css.py — do not edit manually */\n\n"
    return header + "\n\n".join(declarations) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate @font-face CSS from local fonts.")
    parser.add_argument(
        "--output",
        default=str(FONTS_DIR / "fonts.css"),
        help="Output CSS file path.",
    )
    args = parser.parse_args()

    registry = load_registry()
    css = build_font_faces(registry)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(css, encoding="utf-8")
    print(f"Generated {output_path} ({len(css)} bytes)")


if __name__ == "__main__":
    main()
